spring:
  datasource:
    url: ENC(3osjggnH/eMDJdk+amCZ37I04q9L4zS8M+GKDDim1yPhpcTsqtxaoPxxt+hZJjRK/iJHHwFufS5cOmmPz2Obmw==)
    username: ENC(ihpARhocPlg5lL/JzHiQBg==)
    password: ENC(RttvCiAcjCjzsZyZuCT4jv8DUgr6I/Qw)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

app:
  server:
    url: ENC(LBV2r4vE/yMeNeqQfcPDg4XfeblfJieg)
