spring:
  datasource:
    url: ENC(DkBjzzFPXroqHAPpx38cbsNEW/gDW+km0yH5giBBTtYcbVm6cdmAeE8hkiKdrsEQq/Bt6UF603qr0Lyp2oHvuxqMZWHIbSVsxMbsu8CjJZ2n0gvIPxI20g==)
    username: ENC(AoCeej33qfheUlcxWWBiQA==)
    password: ENC(elKaMQowOytkUTRG2gPA0VpmFZAJjO39)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
app:
  server:
    url: http://localhost:8080
