spring:
  application:
    name: GONGGANG-SERVER
  datasource:
    url: ENC(Ai/NpESFYfeoSWDeD2ZC+kqVSzoXX/F59jDvapqK8lZ2FYVQDkailJOzZ3afW/bwVDRJR+YzMVk=)
    username: ENC(YQ6vR9hA4ELUqbKswL0rUA==)
    password: ENC(WODErBsIrO5OXODEbf09NZYw/Csvi968)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  data:
    redis:
      host: ENC(yjPGZuwAsZazfN9YsO8PFqHphetNYjEA)
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(97Dd6ms+JA/E9GuNdnceezMHrJt1y1JopdfSje5q44Ax8bqvnTPJEqtPUk3X6q3U)
            client-secret: ENC(gey7e14CRpmo9hN7REH2rQokfOgVk1VaoELUhdRoR9XdpV9nW92n771302ckEYud)
            redirect-uri: ENC(bCTd4UKNxE+gjetbd9ECT9EQaRKjC9Z0OXDO/+c1mgtH7j3AcHfneHxjOtUlgrxOihIrlqGjFOk=)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

aws-property:
  s3-bucket-name: ENC(e+Cwi1Ov/JY10MANkePGpHh5RGLQG35m)
  access-key: ENC(eOFgsyG9NtbczQqZ03G8SU61SU70XHuYauFECejGgK4=)
  secret-key: ENC(5PM8joGyf8nJLh9xJpvWPIWxT5cjHH3J5O+LMk6W3dzuXE3yEaL2G65KPYgIy2zaHNqzwuIAtDQ=)
  aws-region: ENC(SgyprOhxXFKYQcsT0lRTqfGkGdt90gg3)
  cloudfront:
    url: ENC(NYsFpWlzY27hQxr8qOfHAJ/uzjXFRVAXTG0CzlnenKIi+1i4WFAIxkPROI/4nC0w)

jwt:
  secret: ENC(VIQTMU7Fj420n7rn5zF52KCnt9D57+M8AtUodATEmcYEWLCT5GqkRg==)
  access-token-expire-time: ENC(18YyHLZPfrsAFftbU85GvKAsYA1ZfxjJ)
  refresh-token-expire-time: ENC(tSmeJoRjo5aFk8U1/2mAxJuaZwGAqOvW)

app:
  server:
    url: ENC(mZMq0FTVxHm3sBzz0xLDYEyaweHVXmZ8bOMxFFKZ3ogqxJkUi80wzw==)
  fast-api:
    url: ${FAST_API_URL}

cors:
  allowed-origins: ENC(1lSQMVd68WuQHqDOBUQnTmGOs6lUvXya4oahsNrSUZfYfi+L2iPIUZO7gcI6AYhBuIIw47Gs61l+a5Z6vpYJ3jlkdzI/27HrKu80NJopVrsF8kjJa4bzgfskxar6KDeC/QMh416PZrpMlWRvYM9CaT4k3GkvwcujQx3He47UX8EyaN77IzFFR3UlrywB1wrU7sNCPJbtupdF/xexS2CCybDQ/jmB3xz/HdnGy3aYFbVZxNovBNFSlQ==)

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: ENC(RW5QDK0Was92tPek+CXFrRfozpoxc30rWUWbpHW0qHm2pt6DhBr15Xj5FKaxZmpNvtoOB3GcN2Y=)
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

sentry:
  dsn: ENC(QNMnWxxKpRvdt8q3T/eY0aWMKuL6jfUfFOaThvo9cAL19SjjvcLCJeHxsVmXj0o8PpBRHEowaOfbVEDyXjEc08pdzlvZH3brSAqkZeK94zSXl7TlBvHqtJjgfTRacv/5NKltEh79/NM=)
  environment: ENC(4hyMvAYdy0XB/v2IOgdySg==)
  servername: ENC(T/8gB0RZGKr8XTyK1/iye/HVI3ocbdyq)

logging:
  config: classpath:logback-spring.xml
  sentry:
    repository-uri: ${SENTRY_REPOSITORY_URI}
    environment: prod
    discord-webhook-url: ${DISCORD_WEBHOOK_URL}
    discord-avatar-url: ${DISCORD_AVATAR_URL}
