spring:
  application:
    name: GONGGANG-SERVER
  datasource:
    url: jdbc:mysql://localhost:3306/gonggang
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(/wJ72s2qYsfTkSnat0YKKZuLXbZdUv1UAuGv+bD13KPDJYOTMj/tNf8aDAWNgM3X)
            client-secret: ENC(nMpu85ocSmXSfzqJJ1cWY67/f6Dtk9ndMSMX2MsuTSx9Ww73mwD7FG6tTQZtEAM2)
            redirect-uri: ENC(NSIPnOHpozR41QfwR9PNAK3cQUpr+gar5wGGFp3Ey+2soyuQMNhPsbY+FJlYNK5LaBimhwFhS60=)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

aws-property:
  s3-bucket-name: ENC(ksOSXWEFREJZf22fsOtppTzN3DwsbSmE)
  access-key: ENC(GBspJbqgCs4V9qgwP2Tb270mOOVMfmKD+fJKAvYQzwU=)
  secret-key: ENC(qWeZwBkr6hTjFq0naiqTLF+zab9z2lXyKnzyD9ADe3Vyl5JLEVfAZFF40rk6CQplTu9hJ6QM8Do=)
  aws-region: ENC(Fj3fsOzDypuabZy7pK3wbSNFLj1Pgzub)
  cloudfront:
    url: ENC(p8XEFOOSoqMh3CLzb/yZUorSPKDaJf5H4RB+tNwDvrBxS+2m5KbyaIZaxNJshUw9)

jwt:
  secret: ENC(R0mecsWh3Vw+b0qZEzAkoaEQb0MjS3MKax/QCcfZZBkzJzgqkls2Zw==)
  access-token-expire-time: ENC(dBm8mwq/OPnQmhMGDbuPyWMYQ0P02kAk)
  refresh-token-expire-time: ENC(yArcHcpoAWcT61D/Kjg2bzDbFa65CC8i)

app:
  server:
    url: http://localhost:8080
  fast-api:
    url: ${FAST_API_URL}

cors:
  allowed-origins: ENC(gU9LV9NjOCpKoIWP2mq+NTDPQPMDcWkz2RVoq/V2R4FeKkKYIgP5tnuZs/+Ng4tIBx7lqekWndQDXXzlpEEdtW8E/fioYzIug6Ktiya5eSY=)

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, metrics, prometheus
      base-path: ENC(RW5QDK0Was92tPek+CXFrRfozpoxc30rWUWbpHW0qHm2pt6DhBr15Xj5FKaxZmpNvtoOB3GcN2Y=)
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

sentry:
  dsn: ENC(UxXVXQ47JWIhAIBxWoIqQyOz5KT+XZhSLu/A+1u5GIcHEFRKjBTCdNMc8cYfw1vhkNx0hp+P033/w44AZFuKJwJDgVGc+D9nNtInc+oWLKjp1pS5exFfUCLKD+vzd0p7EP1q+U5lVLM=)
  environment: ENC(bgFhWSzCZxjyTQBHRPA8pw==)
  servername: ENC(bSqg+o6dM1hFIDTuqX8fx4UT3yVGpXhg)

logging:
  config: classpath:logback-spring.xml
  sentry:
    repository-uri: ENC(Fmbmqx7yKowilnGBl3Lxva4511uZMT5wv5xPMo7lxVu+X61BhpSDFMp8R0+Gl3zkA2U1VJ9HsCczf8Zyqv2h2GCjmssPrPNJVx4DsTlvHYDIF2lgobZyspksLsqRy+7t+/uP7b0koMU=)
    environment: local
