spring:
  datasource:
    url: ENC(KZ2mqvwHJ4AjeWPg2+ZZ9exSTpf6A8E+zOGnmGd45yvAkk1iUSuSRg5y+zx16tta)
    username: ENC(ihpARhocPlg5lL/JzHiQBg==)
    password: ENC(RttvCiAcjCjzsZyZuCT4jv8DUgr6I/Qw)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

app:
  server:
    url: ENC(LBV2r4vE/yMeNeqQfcPDg4XfeblfJieg)
