spring:
  datasource:
    url: ENC(a1FOUvfvUn618xVSNf2Ua51Atjf/2SHsL0GE0gRpu0FY3z6oAUBIS+AE9qRZPhGPigfNbclpj7990RVRw4dvhRcff4W4RLOvyQ3XIIRqskx7hfG7ZAoXRQ==)
    username: ENC(PsHF+ccFKU1oUfIIMW5CQw==)
    password: ENC(iyzkesbRcNNDIZQ3CAyEaSbHmODgarHw)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

app:
  server:
    url: ENC(LBV2r4vE/yMeNeqQfcPDg4XfeblfJieg)
