spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gonggang
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

app:
  server:
    url: http://localhost:8080
