spring:
  datasource:
    url: ENC(P/y/en3B7l6XZ4lT6vFm/jotRCGAYHdbcoezdhOzSZbqreb3YsW+ndqPBeXkyhnULD9K4Ql7kqdmYAa1S+mvUXShjmK7IasJFcc9TseoWJL+a9kigKs0wg==)
    username: ENC(AoCeej33qfheUlcxWWBiQA==)
    password: ENC(elKaMQowOytkUTRG2gPA0VpmFZAJjO39)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(/wJ72s2qYsfTkSnat0YKKZuLXbZdUv1UAuGv+bD13KPDJYOTMj/tNf8aDAWNgM3X)
            client-secret: ENC(nMpu85ocSmXSfzqJJ1cWY67/f6Dtk9ndMSMX2MsuTSx9Ww73mwD7FG6tTQZtEAM2)
            redirect-uri: ENC(NSIPnOHpozR41QfwR9PNAK3cQUpr+gar5wGGFp3Ey+2soyuQMNhPsbY+FJlYNK5LaBimhwFhS60=)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

aws-property:
  s3-bucket-name: ENC(ksOSXWEFREJZf22fsOtppTzN3DwsbSmE)
  access-key: ENC(GBspJbqgCs4V9qgwP2Tb270mOOVMfmKD+fJKAvYQzwU=)
  secret-key: ENC(qWeZwBkr6hTjFq0naiqTLF+zab9z2lXyKnzyD9ADe3Vyl5JLEVfAZFF40rk6CQplTu9hJ6QM8Do=)
  aws-region: ENC(Fj3fsOzDypuabZy7pK3wbSNFLj1Pgzub)
  cloudfront:
    url: ENC(p8XEFOOSoqMh3CLzb/yZUorSPKDaJf5H4RB+tNwDvrBxS+2m5KbyaIZaxNJshUw9)

jwt:
  secret: ENC(R0mecsWh3Vw+b0qZEzAkoaEQb0MjS3MKax/QCcfZZBkzJzgqkls2Zw==)
  access-token-expire-time: ENC(dBm8mwq/OPnQmhMGDbuPyWMYQ0P02kAk)
  refresh-token-expire-time: ENC(yArcHcpoAWcT61D/Kjg2bzDbFa65CC8i)

app:
  server:
    url: http://localhost:8080
  fast-api:
    url: ${FAST_API_URL}

cors:
  allowed-origins: ENC(qFgoWc/mLfAl4B4+z3uyoQfyZiosWFDrvlFaeYarOBhAZMOfzcKjLlEIKvhFbrIgM6wtwLBVX8c=)
