spring:
  datasource:
    url: ENC(3kLHK0nREngrnc7SKqEjpwr6erUktiIMOtV8nThJ6D0tMyXfGpujZrpZTaQAMz6t+aXfazgh/iHrtC+oAsFl9boxFfdKRx8V7fOkN5TmcFzQ1IwHU+Bb1g==)
    username: ENC(PsHF+ccFKU1oUfIIMW5CQw==)
    password: ENC(iyzkesbRcNNDIZQ3CAyEaSbHmODgarHw)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  data:
    redis:
      host: ENC(XAMM6J374+ObwFZ0+j+eYcaVzqjoiLW/)
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(97Dd6ms+JA/E9GuNdnceezMHrJt1y1JopdfSje5q44Ax8bqvnTPJEqtPUk3X6q3U)
            client-secret: ENC(gey7e14CRpmo9hN7REH2rQokfOgVk1VaoELUhdRoR9XdpV9nW92n771302ckEYud)
            redirect-uri: ENC(dqsfPhntrRwFVkHXL2CedLcWwQW4jtILcTe1adahjwnKji+quxKi8GihvPZVv7vp187yY+/Sf+kUGQJ8+SOzVw==)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

aws-property:
  s3-bucket-name: ENC(e+Cwi1Ov/JY10MANkePGpHh5RGLQG35m)
  access-key: ENC(eOFgsyG9NtbczQqZ03G8SU61SU70XHuYauFECejGgK4=)
  secret-key: ENC(5PM8joGyf8nJLh9xJpvWPIWxT5cjHH3J5O+LMk6W3dzuXE3yEaL2G65KPYgIy2zaHNqzwuIAtDQ=)
  aws-region: ENC(SgyprOhxXFKYQcsT0lRTqfGkGdt90gg3)
  cloudfront:
    url: ENC(NYsFpWlzY27hQxr8qOfHAJ/uzjXFRVAXTG0CzlnenKIi+1i4WFAIxkPROI/4nC0w)

jwt:
  secret: ENC(VIQTMU7Fj420n7rn5zF52KCnt9D57+M8AtUodATEmcYEWLCT5GqkRg==)
  access-token-expire-time: ENC(qsTJOF17xHFt3kWKPTuRUQ==)
  refresh-token-expire-time: ENC(tSmeJoRjo5aFk8U1/2mAxJuaZwGAqOvW)

app:
  server:
    url: ENC(OqXzdllHjTlA0R8KgCf1VkFvbWOlb9OtjmqEofP/rrUMk2QFH0uZsg==)

cors:
  allowed-origins: ENC(1cU+Mpg3zzzXFDwuibpDQ4ctFviqp4in6mrEHmEBsT7Wam1JdTvoq2r1fk1Bkt9AsyZIkRXpHQWTNSmEFZt19RzR1xIAuVXhO8DAtblfV78l/jqrOtbKPQ==)
