spring:
  datasource:
    url: ENC(P/y/en3B7l6XZ4lT6vFm/jotRCGAYHdbcoezdhOzSZbqreb3YsW+ndqPBeXkyhnULD9K4Ql7kqdmYAa1S+mvUXShjmK7IasJFcc9TseoWJL+a9kigKs0wg==)
    username: ENC(AoCeej33qfheUlcxWWBiQA==)
    password: ENC(elKaMQowOytkUTRG2gPA0VpmFZAJjO39)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

cloud:
  aws:
    cloudfront:
      url: ENC(p8XEFOOSoqMh3CLzb/yZUorSPKDaJf5H4RB+tNwDvrBxS+2m5KbyaIZaxNJshUw9)
    s3:
      bucket: ENC(ksOSXWEFREJZf22fsOtppTzN3DwsbSmE)
    region:
      static: ENC(Fj3fsOzDypuabZy7pK3wbSNFLj1Pgzub)
    credentials:
      accessKey: ENC(GBspJbqgCs4V9qgwP2Tb270mOOVMfmKD+fJKAvYQzwU=)
      secretKey: ENC(qWeZwBkr6hTjFq0naiqTLF+zab9z2lXyKnzyD9ADe3Vyl5JLEVfAZFF40rk6CQplTu9hJ6QM8Do=)

app:
  server:
    url: http://localhost:8080
